// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUyekF5IANxMSrHCDSy5VCu-VsjJh08xg',
    appId: '1:650001200852:web:c51ecb9e6b5450ca0a6d41',
    messagingSenderId: '650001200852',
    projectId: 'votaciones-659a9',
    authDomain: 'votaciones-659a9.firebaseapp.com',
    storageBucket: 'votaciones-659a9.appspot.com',
    measurementId: 'G-HKVPGQDMWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJOHlivOeYc148AraFuCee8YNuiFCZvmA',
    appId: '1:650001200852:android:f30c759b248943400a6d41',
    messagingSenderId: '650001200852',
    projectId: 'votaciones-659a9',
    storageBucket: 'votaciones-659a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihUyjEjq_aR-OmaHQYUYbt_uR541t7N4',
    appId: '1:650001200852:ios:2005b818d48299880a6d41',
    messagingSenderId: '650001200852',
    projectId: 'votaciones-659a9',
    storageBucket: 'votaciones-659a9.appspot.com',
    iosBundleId: 'com.example.votaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihUyjEjq_aR-OmaHQYUYbt_uR541t7N4',
    appId: '1:650001200852:ios:2005b818d48299880a6d41',
    messagingSenderId: '650001200852',
    projectId: 'votaciones-659a9',
    storageBucket: 'votaciones-659a9.appspot.com',
    iosBundleId: 'com.example.votaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUyekF5IANxMSrHCDSy5VCu-VsjJh08xg',
    appId: '1:650001200852:web:8d8563bf458f196f0a6d41',
    messagingSenderId: '650001200852',
    projectId: 'votaciones-659a9',
    authDomain: 'votaciones-659a9.firebaseapp.com',
    storageBucket: 'votaciones-659a9.appspot.com',
    measurementId: 'G-2JLFQ7GXWB',
  );
}
